### ISSUE TITLE
Latest version causing insane worker CPU usage

### ISSUE THREAD

**Issue by adrianpaiva1** [udokmeci/yii2-beanstalk#36] opened 2017-10-03 17:56 UTC
I just updated to your latest version and all of workers (running with supervisor) started going crazy (400%) total server cpu usage.

I'm running php 7.1. I just downgraded back to 1.0.1 and everything seems fine again.

**Comment by udokmeci** [comment] 2017-10-04 05:37
@adrianpaiva1 This is probably beacuse of the 'ticks' are removed. You can use it like this or can add 'sleep' to your controller. 
To investigate it further can you please let me know which version of php you are using?
Thanks,

**Comment by adrianpaiva1** [comment] 2017-10-05 20:25
Hi I'm running PHP 7.1.71. Thanks for looking into this, love this library!

**Comment by udokmeci** [comment] 2017-10-06 05:29
Hi again,
Sleep 3 is very low i mean you can set it something like 100. It is ms. Still it should reduce CPU usage, did it?
Thank you for support.

**Comment by drsdre** [comment] 2017-10-10 14:24
Hi, I have the same issue since I installed the last version. 

This is the unchanged config which causes high CPU load on both the PHP worker process and the beanstalk process:
'beanstalk'    => [
			'class'          => 'udokmeci\yii2beanstalk\Beanstalk',
			'host'           => '127.0.0.1',
			'port'           => 11300,
			'connectTimeout' => 1,
			'sleep'          => 60,
		],

I've changed the sleep value to 1000, but not no avail.

A different software package that uses the previous version of yii2-beanstalk uses sleep 60 to and does not show out of bound CPU usage.

Andre

**Comment by drsdre** [comment] 2017-10-10 21:33
It looks like the issue is pointing to getting a RESPONSE_TIMED_OUT whilst trying to reserve the tube in beforeAction of BeanstalkController.php (lines 303-320):

```
$job = $bean->reserve(0);
if (!$job) {
  continue;
}
```

**Comment by drsdre** [comment] 2017-10-10 22:32
Added pull request #37 to make CPU load manageable through sleep.

**Comment by udokmeci** [comment] 2017-10-11 06:00
Thanks merged and released! Controller or Component could also have a default timeout for reserve method.

**Closed by udokmeci** 2017-10-11 06:00 UTC
